binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions:
  TemplateHaskell: true
  QuasiQuotes: true
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'RepLib: 0.5.3.3

  Hackage: unbound 0.4.3.1

  Hackage: alex-meta 0.3.0.7

  Hackage: happy-meta 0.2.0.7

  Hackage: BNFC-meta 0.4.0.2'
ghc-args:
- -Wall
excluded-modules: []
